#!/bin/bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "============================================"
echo "  Serverless Agentic Image Editor - Destroy"
echo "============================================"
echo ""

# Check AWS credentials
echo "Checking AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
  echo -e "${RED}[ERROR]${NC} AWS credentials not configured or expired."
  echo "Please configure AWS credentials before destroying the stack."
  exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
REGION=$(aws configure get region 2>/dev/null || echo "us-east-1")
echo -e "${GREEN}[OK]${NC} AWS credentials valid. Account: $ACCOUNT_ID, Region: $REGION"

echo ""
echo "Installing dependencies..."
npm install

echo ""
echo "Destroying ImageEditorStack..."
cdk destroy --force || true

echo ""
echo "Cleaning up orphaned AgentCore resources..."

for HID in $(aws bedrock-agentcore-control list-harnesses --region "$REGION" --query "harnesses[?starts_with(harnessName,'img_editor')].harnessId" --output text 2>/dev/null); do
  echo "  Deleting harness: $HID"
  aws bedrock-agentcore-control delete-harness --harness-id "$HID" --region "$REGION" 2>/dev/null || true
done

for MID in $(aws bedrock-agentcore-control list-memories --region "$REGION" --query "memories[?starts_with(name,'img_editor')].id" --output text 2>/dev/null); do
  echo "  Deleting memory: $MID"
  aws bedrock-agentcore-control delete-memory --memory-id "$MID" --region "$REGION" 2>/dev/null || true
done

echo ""
echo -e "${YELLOW}The S3 bucket contains images generated by this application.${NC}"
read -p "Do you want to delete the S3 bucket and all stored images? (yes/no) " DELETE_BUCKET
if [ "$DELETE_BUCKET" = "yes" ]; then
  echo "Cleaning up S3 buckets..."
  for BUCKET in $(aws s3api list-buckets --query "Buckets[?starts_with(Name,'imageeditorstack-')].Name" --output text 2>/dev/null); do
    echo "  Emptying bucket: $BUCKET"
    aws s3 rm "s3://$BUCKET" --recursive --region "$REGION" 2>/dev/null || true
    echo "  Deleting bucket: $BUCKET"
    aws s3api delete-bucket --bucket "$BUCKET" --region "$REGION" 2>/dev/null || true
  done
else
  echo "S3 bucket retained. To delete later:"
  for BUCKET in $(aws s3api list-buckets --query "Buckets[?starts_with(Name,'imageeditorstack-')].Name" --output text 2>/dev/null); do
    echo "  aws s3 rm s3://$BUCKET --recursive && aws s3api delete-bucket --bucket $BUCKET"
  done
fi

echo ""
echo -e "${GREEN}Done.${NC} All resources cleaned up."

# Clean up local artifacts
if [ -f cdk-outputs.json ]; then
  rm cdk-outputs.json
fi
