#!/bin/bash
set -e

# Disable the AWS CLI v2 pager. Without this, commands whose JSON output is not
# captured (e.g. delete-harness) pipe through `less` and pause at a ':' prompt,
# silently blocking the script until the user presses q.
export AWS_PAGER=""

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "============================================"
echo "  Serverless Agentic Image Editor - Destroy"
echo "============================================"
echo ""

# Check AWS credentials
echo "Checking AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
  echo -e "${RED}[ERROR]${NC} AWS credentials not configured or expired."
  echo "Please configure AWS credentials before destroying the stack."
  exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
REGION=$(aws configure get region 2>/dev/null || echo "us-east-1")
echo -e "${GREEN}[OK]${NC} AWS credentials valid. Account: $ACCOUNT_ID, Region: $REGION"

echo ""
echo "Installing dependencies..."
npm install

echo ""
echo "Deleting AgentCore resources (before stack destroy to preserve IAM role)..."

# Delete each harness and wait for it to fully disappear. The execution role
# still exists at this point (cdk destroy runs later), which the harness needs
# to tear down its runtime. A harness in DELETE_FAILED is retried until gone.
delete_harness_and_wait() {
  HID="$1"
  for attempt in $(seq 1 24); do
    STATUS=$(aws bedrock-agentcore-control get-harness --harness-id "$HID" --region "$REGION" --query "harness.status" --output text 2>/dev/null || echo "GONE")
    if [ "$STATUS" = "GONE" ]; then
      echo "    Harness $HID deleted."
      return 0
    fi
    if [ "$STATUS" = "DELETING" ]; then
      sleep 10
      continue
    fi
    # READY or *_FAILED (incl. DELETE_FAILED): (re)issue delete
    echo "    Harness $HID status=$STATUS, issuing delete..."
    aws bedrock-agentcore-control delete-harness --harness-id "$HID" --region "$REGION" 2>/dev/null || true
    sleep 10
  done
  echo -e "    ${YELLOW}Warning:${NC} harness $HID did not delete in time."
  return 1
}

for HID in $(aws bedrock-agentcore-control list-harnesses --region "$REGION" --query "harnesses[?starts_with(harnessName,'img_editor')].harnessId" --output text 2>/dev/null); do
  echo "  Deleting harness: $HID"
  aws bedrock-agentcore-control delete-harness --harness-id "$HID" --region "$REGION" 2>/dev/null || true
  delete_harness_and_wait "$HID"
done

for MID in $(aws bedrock-agentcore-control list-memories --region "$REGION" --query "memories[?contains(id,'img_editor')].id" --output text 2>/dev/null); do
  echo "  Deleting memory: $MID"
  aws bedrock-agentcore-control delete-memory --memory-id "$MID" --region "$REGION" 2>/dev/null || true
done

echo ""
echo "Destroying ImageEditorStack..."
npx cdk destroy --force || true

echo ""
echo "Cleaning up any remaining orphaned resources..."

for HID in $(aws bedrock-agentcore-control list-harnesses --region "$REGION" --query "harnesses[?starts_with(harnessName,'img_editor')].harnessId" --output text 2>/dev/null); do
  echo "  Retrying harness delete: $HID"
  aws bedrock-agentcore-control delete-harness --harness-id "$HID" --region "$REGION" 2>/dev/null || true
done

for MID in $(aws bedrock-agentcore-control list-memories --region "$REGION" --query "memories[?contains(id,'img_editor')].id" --output text 2>/dev/null); do
  echo "  Deleting memory: $MID"
  aws bedrock-agentcore-control delete-memory --memory-id "$MID" --region "$REGION" 2>/dev/null || true
done

echo ""
echo -e "${YELLOW}The S3 bucket contains images generated by this application.${NC}"
read -p "Do you want to delete the S3 bucket and all stored images? (yes/no) " DELETE_BUCKET
if [ "$DELETE_BUCKET" = "yes" ]; then
  echo "Cleaning up S3 buckets..."
  for BUCKET in $(aws s3api list-buckets --query "Buckets[?starts_with(Name,'imageeditorstack-')].Name" --output text 2>/dev/null); do
    echo "  Emptying bucket: $BUCKET"
    aws s3 rm "s3://$BUCKET" --recursive --region "$REGION" 2>/dev/null || true
    echo "  Deleting bucket: $BUCKET"
    aws s3api delete-bucket --bucket "$BUCKET" --region "$REGION" 2>/dev/null || true
  done
else
  echo "S3 bucket retained. To delete later:"
  for BUCKET in $(aws s3api list-buckets --query "Buckets[?starts_with(Name,'imageeditorstack-')].Name" --output text 2>/dev/null); do
    echo "  aws s3 rm s3://$BUCKET --recursive && aws s3api delete-bucket --bucket $BUCKET"
  done
fi

echo ""
echo -e "${GREEN}Done.${NC} All resources cleaned up."

# Clean up local artifacts
if [ -f cdk-outputs.json ]; then
  rm cdk-outputs.json
fi
